-- S128 Part H, section 1 of 2 — COST CODES and the COMPANY DIVISION TEMPLATE.
-- ⚠️ PART H IS REBUILD-TEST ONLY. NOT MERGED. NEVER APPLIED TO PRODUCTION (S128 prompt, stop rule 1).
--
-- docs/specs/estimates-and-change-orders-spec.md H-1, H-2, H-7, H-12;
-- docs/specs/cost-codes-masterformat-1995.md § 1 (the format) and § 4 (the seed, 88 codes).
--
-- H-2 ⚠️ A cost code is FIVE characters of TEXT, zero-padded ('01000'), never a number. The CHECK
-- refuses anything else, and the division is read from the first two characters as TEXT
-- (division_code is generated by left(code, 2)), so '01000' files under '01', never '10'.
--
-- SEEDING IS LAZY, not a trigger on companies: enable_division_budget() (section 2) seeds a
-- company the first time it turns division budgeting on. A seed-on-insert trigger is what left
-- 109 orphan companies on rebuild-test (S147, test-support/company-purge.ts), and every table
-- here CASCADES from companies for the same reason — they are configuration, never history.
--
-- Read: the codes and the division names are not money, so every staff role reads them (the
-- separate expenses build will file expenses by code). The BOTTOM-BLOCK TEMPLATE carries rates
-- (a GC fee is margin), so it is Owner/Admin only — like instrument_rates. Writes: Owner/Admin.

-- ── 1. company_cost_codes ────────────────────────────────────────────────────
CREATE TABLE public.company_cost_codes (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id    uuid NOT NULL DEFAULT public.get_my_company_id() REFERENCES public.companies(id) ON DELETE CASCADE,
  code          text NOT NULL CONSTRAINT company_cost_codes_code_format CHECK (code ~ '^[0-9]{5}$'),
  division_code text GENERATED ALWAYS AS (left(code, 2)) STORED,
  title         text NOT NULL CHECK (char_length(btrim(title)) > 0),
  in_use_seed   boolean NOT NULL DEFAULT false,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  created_by    uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by    uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  is_deleted    boolean NOT NULL DEFAULT false,
  deleted_at    timestamptz
);
CREATE INDEX idx_company_cost_codes_company_id ON public.company_cost_codes (company_id);
CREATE UNIQUE INDEX idx_company_cost_codes_company_code_live
  ON public.company_cost_codes (company_id, code) WHERE is_deleted = false;
COMMENT ON COLUMN public.company_cost_codes.code IS
  'S128 H-2: MasterFormat 1995 DDSSS, five characters of TEXT, zero-padded. Never a number.';
ALTER TABLE public.company_cost_codes ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER company_cost_codes_updated_at BEFORE UPDATE ON public.company_cost_codes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE OR REPLACE FUNCTION public.set_company_cost_codes_updated_by()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_by = auth.uid(); RETURN NEW; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE TRIGGER company_cost_codes_set_updated_by BEFORE UPDATE ON public.company_cost_codes
  FOR EACH ROW EXECUTE FUNCTION public.set_company_cost_codes_updated_by();

CREATE POLICY company_cost_codes_select_staff ON public.company_cost_codes
  FOR SELECT TO authenticated
  USING (company_id = public.get_my_company_id()
         AND public.get_my_role() = ANY (ARRAY['owner','admin','project_executive','project_manager','foreman','crew_member']));
CREATE POLICY company_cost_codes_insert_owner_admin ON public.company_cost_codes
  FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));
CREATE POLICY company_cost_codes_update_owner_admin ON public.company_cost_codes
  FOR UPDATE TO authenticated
  USING (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']))
  WITH CHECK (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));

-- ── 2. company_divisions (the default division set, H-1) ─────────────────────
CREATE TABLE public.company_divisions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id  uuid NOT NULL DEFAULT public.get_my_company_id() REFERENCES public.companies(id) ON DELETE CASCADE,
  code        text NOT NULL CONSTRAINT company_divisions_code_format CHECK (code ~ '^[0-9]{2}$'),
  name        text NOT NULL CHECK (char_length(btrim(name)) > 0),
  sort_order  integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  created_by  uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by  uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  is_deleted  boolean NOT NULL DEFAULT false,
  deleted_at  timestamptz
);
CREATE INDEX idx_company_divisions_company_id ON public.company_divisions (company_id);
ALTER TABLE public.company_divisions ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER company_divisions_updated_at BEFORE UPDATE ON public.company_divisions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE OR REPLACE FUNCTION public.set_company_divisions_updated_by()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_by = auth.uid(); RETURN NEW; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE TRIGGER company_divisions_set_updated_by BEFORE UPDATE ON public.company_divisions
  FOR EACH ROW EXECUTE FUNCTION public.set_company_divisions_updated_by();

CREATE POLICY company_divisions_select_staff ON public.company_divisions
  FOR SELECT TO authenticated
  USING (company_id = public.get_my_company_id()
         AND public.get_my_role() = ANY (ARRAY['owner','admin','project_executive','project_manager','foreman','crew_member']));
CREATE POLICY company_divisions_insert_owner_admin ON public.company_divisions
  FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));
CREATE POLICY company_divisions_update_owner_admin ON public.company_divisions
  FOR UPDATE TO authenticated
  USING (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']))
  WITH CHECK (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));

-- ── 3. company_bottom_template_lines (the block below the divisions, H-7) ────
-- charge_mode: 'amount' (flat) · 'base' (mode 1, a % of what sits above) · 'total' (mode 2,
-- a % of the final total including itself — the gross-up). kind is the label family.
CREATE TABLE public.company_bottom_template_lines (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id   uuid NOT NULL DEFAULT public.get_my_company_id() REFERENCES public.companies(id) ON DELETE CASCADE,
  name         text NOT NULL CHECK (char_length(btrim(name)) > 0),
  kind         text NOT NULL CHECK (kind IN ('flat','percent','contingency','allowance','bond')),
  charge_mode  text NOT NULL CHECK (charge_mode IN ('amount','base','total')),
  rate         numeric(9,4) CHECK (rate IS NULL OR rate >= 0),
  amount       numeric(14,2),
  sort_order   integer NOT NULL DEFAULT 0,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  created_by   uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by   uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  is_deleted   boolean NOT NULL DEFAULT false,
  deleted_at   timestamptz
);
CREATE INDEX idx_company_bottom_template_lines_company_id ON public.company_bottom_template_lines (company_id);
ALTER TABLE public.company_bottom_template_lines ENABLE ROW LEVEL SECURITY;
CREATE TRIGGER company_bottom_template_lines_updated_at BEFORE UPDATE ON public.company_bottom_template_lines
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE OR REPLACE FUNCTION public.set_company_bottom_template_lines_updated_by()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_by = auth.uid(); RETURN NEW; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
CREATE TRIGGER company_bottom_template_lines_set_updated_by BEFORE UPDATE ON public.company_bottom_template_lines
  FOR EACH ROW EXECUTE FUNCTION public.set_company_bottom_template_lines_updated_by();

CREATE POLICY company_bottom_template_lines_select_owner_admin ON public.company_bottom_template_lines
  FOR SELECT TO authenticated
  USING (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));
CREATE POLICY company_bottom_template_lines_insert_owner_admin ON public.company_bottom_template_lines
  FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));
CREATE POLICY company_bottom_template_lines_update_owner_admin ON public.company_bottom_template_lines
  FOR UPDATE TO authenticated
  USING (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']))
  WITH CHECK (company_id = public.get_my_company_id() AND public.get_my_role() = ANY (ARRAY['owner','admin']));

-- ── 4. The seed — called by enable_division_budget(), never by a trigger ─────
-- Idempotent per table: a company that already has rows in a table is left alone there.
-- The GC Fee / GL / Builders Risk RATES are PLACEHOLDERS (10 / 2 / 1), editable per company and
-- per estimate; Josh's sheet names the lines but the spec gives no rates (S128 report, ASK-H1).
CREATE OR REPLACE FUNCTION public.seed_company_division_defaults(p_company_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM company_cost_codes WHERE company_id = p_company_id) THEN
    INSERT INTO company_cost_codes (company_id, code, title, in_use_seed)
    SELECT p_company_id, v.code, v.title, v.in_use FROM (VALUES
    ('01000', 'General Conditions', true),
    ('01100', 'Summary of work', false),
    ('01200', 'Price & payment procedures', false),
    ('01310', 'Project coordination', false),
    ('01330', 'Submittals', false),
    ('01400', 'Quality requirements', false),
    ('01500', 'Temporary facilities & controls', false),
    ('01600', 'Product requirements', false),
    ('01700', 'Execution & closeout', false),
    ('01740', 'Cleaning', false),
    ('02080', 'Hazardous material abatement', true),
    ('02110', 'Site clearing', true),
    ('02200', 'Sitework / earthwork', true),
    ('02280', 'Surveying & layout', true),
    ('02300', 'Excavation & fill', false),
    ('02510', 'Paving & curbing', true),
    ('02600', 'Sewer & lift station', true),
    ('02660', 'Water distribution', true),
    ('02661', 'DDCV / fire line', true),
    ('02721', 'Drainage', true),
    ('02810', 'Irrigation', true),
    ('02900', 'Landscaping & planting', true),
    ('03100', 'Concrete forming', false),
    ('03200', 'Concrete reinforcing', false),
    ('03300', 'Cast-in-place concrete', false),
    ('03350', 'Concrete finishing', false),
    ('03400', 'Precast concrete', false),
    ('04200', 'Unit masonry', false),
    ('04220', 'Concrete unit masonry / concrete shell', true),
    ('04270', 'Cladding', true),
    ('04400', 'Stone', false),
    ('05120', 'Structural steel', true),
    ('05210', 'Steel joists', false),
    ('05310', 'Steel deck', false),
    ('05500', 'Metal fabrications', true),
    ('05520', 'Handrails & railings', false),
    ('06100', 'Rough carpentry / roof carpentry', true),
    ('06190', 'Wood trusses', true),
    ('06200', 'Finish carpentry', false),
    ('06220', 'Millwork / exterior wood brackets', true),
    ('06400', 'Architectural woodwork', true),
    ('07100', 'Waterproofing & damproofing', false),
    ('07200', 'Insulation / open cell foam', true),
    ('07500', 'Membrane roofing', false),
    ('07510', 'Roofing', true),
    ('07600', 'Flashing & sheet metal', false),
    ('07840', 'Firestopping', false),
    ('07900', 'Joint sealants / caulking', true),
    ('08110', 'Steel doors & frames', false),
    ('08200', 'Wood & plastic doors', false),
    ('08500', 'Windows', false),
    ('08700', 'Hardware', false),
    ('08800', 'Glazing', false),
    ('09200', 'Plaster & stucco', true),
    ('09250', 'Gypsum board / drywall', true),
    ('09300', 'Tile', false),
    ('09500', 'Acoustical ceilings', true),
    ('09540', 'Specialty ceilings & siding', true),
    ('09650', 'Resilient flooring', false),
    ('09680', 'Carpet / flooring', true),
    ('09900', 'Painting', false),
    ('09920', 'Interior painting', true),
    ('10200', 'Louvers & vents', false),
    ('10440', 'Signage', false),
    ('10536', 'Pergolas & canopies', true),
    ('10550', 'Aluminum sunshades', true),
    ('10800', 'Toilet accessories', true),
    ('11400', 'Food service equipment', false),
    ('11450', 'Residential appliances', false),
    ('12300', 'Casework & cabinets', false),
    ('12500', 'Furniture (FF&E)', false),
    ('12900', 'Furnishings accessories', false),
    ('13100', 'Lightning protection', false),
    ('13150', 'Swimming pools', false),
    ('13900', 'Fire suppression', false),
    ('14200', 'Elevators', false),
    ('14300', 'Escalators & moving walks', false),
    ('15300', 'Fire protection / sprinklers', false),
    ('15400', 'Plumbing', false),
    ('15410', 'Plumbing fixtures', false),
    ('15500', 'Heating', false),
    ('15700', 'HVAC', false),
    ('15800', 'Air distribution', false),
    ('16000', 'Electrical', true),
    ('16100', 'Wiring methods', false),
    ('16500', 'Lighting', false),
    ('16600', 'Fire alarm', true),
    ('16700', 'Communications & low voltage', false)
    ) AS v(code, title, in_use);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM company_divisions WHERE company_id = p_company_id) THEN
    INSERT INTO company_divisions (company_id, code, name, sort_order)
    SELECT p_company_id, v.code, v.name, v.sort_order FROM (VALUES
    ('01', 'General Requirements', 0),
    ('02', 'Sitework', 1),
    ('03', 'Concrete', 2),
    ('04', 'Masonry', 3),
    ('05', 'Metals', 4),
    ('06', 'Wood & Plastics', 5),
    ('07', 'Thermal & Moisture Protection', 6),
    ('08', 'Doors & Windows', 7),
    ('09', 'Finishes', 8),
    ('10', 'Specialties', 9),
    ('11', 'Equipment', 10),
    ('12', 'Furnishings', 11),
    ('13', 'Special Construction', 12),
    ('14', 'Conveying Systems', 13),
    ('15', 'Mechanical', 14),
    ('16', 'Electrical', 15)
    ) AS v(code, name, sort_order);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM company_bottom_template_lines WHERE company_id = p_company_id) THEN
    INSERT INTO company_bottom_template_lines (company_id, name, kind, charge_mode, rate, amount, sort_order)
    VALUES
      (p_company_id, 'GC Fee',        'percent', 'base',  10, NULL, 0),
      (p_company_id, 'GL Insurance',  'percent', 'total',  2, NULL, 1),
      (p_company_id, 'Builders Risk', 'percent', 'base',   1, NULL, 2);
  END IF;
END;
$function$;
REVOKE ALL ON FUNCTION public.seed_company_division_defaults(uuid) FROM PUBLIC, anon, authenticated;
