-- ============================================================================
-- CHAT — mark-read must be stamped by the DATABASE, not by the client.
-- ============================================================================
--
-- ⚠️ THIS IS A BUG FIX, FOUND BY A FAILING LIVE TEST, AND THE TEST WAS RIGHT.
--
-- `markThreadRead()` upserted `chat_reads.last_read_at` with
-- `new Date().toISOString()` — the CLIENT clock. Every value it is ever
-- compared against is `chat_messages.created_at`, stamped by `now()` — the
-- DATABASE clock. The unread count is `created_at > last_read_at`, so the two
-- clocks are subtracted from each other on every read.
--
-- WHAT THAT COSTS WHEN THE CLIENT RUNS FAST: `last_read_at` lands in the
-- database's future, every subsequent message compares as already-read, and the
-- unread badge silently never lights. There is nothing to see — the thread just
-- stops telling you anything is new, which is the exact failure chat exists to
-- prevent (§1: requests get lost).
--
-- It is not hypothetical: the S126 live harness failed on it, and the switcher
-- RPC returned the CORRECT count for the same rows when the read row was
-- stamped by the server. The RPC was right; the writer was wrong.
--
-- ⚠️ AND THE MEASUREMENT THAT NEARLY EXONERATED IT WAS INVALID. Comparing a
-- `new Date()` in node with a `now()` from a separate round trip compares two
-- different instants, not two clocks — it cannot show skew and must not be used
-- to rule it out. The only safe rule is the one this migration enforces: a
-- timestamp compared against a server timestamp is generated by the server.
--
-- A plain PostgREST upsert cannot express `SET last_read_at = now()`, so this is
-- an RPC. SECURITY INVOKER, so `chat_reads_insert_own` / `chat_reads_update_own`
-- still decide — a caller cannot mark somebody else's thread read.

CREATE OR REPLACE FUNCTION chat_mark_read(p_thread_id uuid)
RETURNS timestamptz
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path TO 'public'
AS $$
DECLARE
  v_profile_id uuid := get_my_profile_id();
  v_company_id uuid := get_my_company_id();
  v_now        timestamptz;
BEGIN
  IF v_profile_id IS NULL THEN
    RETURN NULL;
  END IF;

  INSERT INTO chat_reads (company_id, profile_id, thread_id, last_read_at)
  VALUES (v_company_id, v_profile_id, p_thread_id, now())
  ON CONFLICT (profile_id, thread_id)
  DO UPDATE SET last_read_at = now()
  RETURNING last_read_at INTO v_now;

  RETURN v_now;
END;
$$;

COMMENT ON FUNCTION chat_mark_read(uuid) IS
  'Marks a chat thread read for the caller, stamped by the SERVER clock. The '
  'client must never supply last_read_at: it is compared against '
  'chat_messages.created_at, and a fast client clock silently suppresses the '
  'unread badge forever. SECURITY INVOKER — chat_reads RLS still applies.';
