-- ═══════════════════════════════════════════════════════════════════════════════
--  IronFrame Pro — Supabase Schema
--  Paste this into the Supabase SQL Editor and click "Run"
-- ═══════════════════════════════════════════════════════════════════════════════

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. users
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists users (
  id            bigint generated by default as identity primary key,
  email         text unique not null,
  password_hash text not null,
  full_name     text not null,
  role          text not null default 'employee'
                check (role in ('owner','foreman','employee','admin','viewer')),
  phone         text,
  company       text,
  avatar_url    text,
  is_active     boolean default true,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. projects
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists projects (
  id            bigint generated by default as identity primary key,
  name          text not null,
  description   text,
  status        text default 'planning'
                check (status in ('planning','active','on_hold','completed','archived')),
  address       text,
  city          text,
  state         text,
  zip           text,
  lat           double precision,
  lng           double precision,
  start_date    date,
  end_date      date,
  budget        numeric default 0,
  owner_id      bigint references users(id),
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. project_members
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists project_members (
  project_id    bigint references projects(id) on delete cascade,
  user_id       bigint references users(id) on delete cascade,
  role          text default 'member',
  primary key (project_id, user_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. contracts
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists contracts (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  title         text not null,
  vendor        text,
  contract_type text default 'subcontract'
                check (contract_type in ('prime','subcontract','purchase_order','service')),
  amount        numeric default 0,
  status        text default 'draft'
                check (status in ('draft','pending','active','completed','cancelled')),
  start_date    date,
  end_date      date,
  file_path     text,
  notes         text,
  created_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. estimates
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists estimates (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  title         text not null,
  description   text,
  status        text default 'draft'
                check (status in ('draft','sent','approved','rejected','revised')),
  total         numeric default 0,
  markup_pct    numeric default 0,
  tax_pct       numeric default 0,
  created_by    bigint references users(id),
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. estimate_line_items
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists estimate_line_items (
  id            bigint generated by default as identity primary key,
  estimate_id   bigint references estimates(id) on delete cascade,
  category      text,
  description   text not null,
  quantity      numeric default 1,
  unit          text default 'ea',
  unit_cost     numeric default 0,
  total         numeric generated always as (quantity * unit_cost) stored,
  sort_order    integer default 0
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. change_orders
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists change_orders (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  co_number     integer not null,
  title         text not null,
  description   text,
  status        text default 'pending'
                check (status in ('pending','approved','rejected','void')),
  amount        numeric default 0,
  requested_by  bigint references users(id),
  approved_by   bigint references users(id),
  approved_at   timestamptz,
  created_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. catalog_items
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists catalog_items (
  id            bigint generated by default as identity primary key,
  code          text unique,
  name          text not null,
  category      text,
  subcategory   text,
  unit          text default 'ea',
  unit_cost     numeric default 0,
  labor_cost    numeric default 0,
  description   text,
  is_active     boolean default true,
  updated_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. bid_requests
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists bid_requests (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  title         text not null,
  scope         text,
  status        text default 'open'
                check (status in ('open','closed','awarded','cancelled')),
  due_date      date,
  created_by    bigint references users(id),
  created_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. bids
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists bids (
  id              bigint generated by default as identity primary key,
  bid_request_id  bigint references bid_requests(id) on delete cascade,
  vendor_name     text not null,
  vendor_email    text,
  amount          numeric,
  notes           text,
  file_path       text,
  is_selected     boolean default false,
  submitted_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. time_entries
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists time_entries (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  user_id       bigint references users(id),
  date          date not null,
  hours         numeric not null,
  description   text,
  cost_code     text,
  is_overtime   boolean default false,
  approved      boolean default false,
  approved_by   bigint references users(id),
  created_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 12. daily_logs
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists daily_logs (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  date          date not null,
  weather       text,
  temp_high     numeric,
  temp_low      numeric,
  wind          text,
  crew_count    integer default 0,
  summary       text,
  safety_notes  text,
  delays        text,
  visitors      text,
  created_by    bigint references users(id),
  created_at    timestamptz default now(),
  unique (project_id, date)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 13. photos
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists photos (
  id            bigint generated by default as identity primary key,
  project_id    bigint references projects(id) on delete cascade,
  daily_log_id  bigint references daily_logs(id),
  file_path     text not null,
  thumbnail     text,
  caption       text,
  tags          text,
  location      text,
  markup_data   jsonb,
  taken_at      timestamptz,
  uploaded_by   bigint references users(id),
  created_at    timestamptz default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 14. notifications
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists notifications (
  id            bigint generated by default as identity primary key,
  user_id       bigint references users(id) on delete cascade,
  type          text not null,
  title         text not null,
  body          text,
  link          text,
  is_read       boolean default false,
  created_at    timestamptz default now()
);

-- ═══════════════════════════════════════════════════════════════════════════════
--  Indexes
-- ═══════════════════════════════════════════════════════════════════════════════
create index if not exists idx_projects_status      on projects(status);
create index if not exists idx_co_project           on change_orders(project_id);
create index if not exists idx_time_user_date       on time_entries(user_id, date);
create index if not exists idx_logs_proj_date       on daily_logs(project_id, date);
create index if not exists idx_photos_project       on photos(project_id);
create index if not exists idx_notif_user           on notifications(user_id, is_read);
create index if not exists idx_catalog_cat          on catalog_items(category);

-- ═══════════════════════════════════════════════════════════════════════════════
--  Auto-update updated_at triggers
-- ═══════════════════════════════════════════════════════════════════════════════
create or replace function update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger trg_users_updated_at
  before update on users
  for each row execute function update_updated_at();

create trigger trg_projects_updated_at
  before update on projects
  for each row execute function update_updated_at();

create trigger trg_estimates_updated_at
  before update on estimates
  for each row execute function update_updated_at();

create trigger trg_catalog_updated_at
  before update on catalog_items
  for each row execute function update_updated_at();
